### ISSUE TITLE
JSoup libraries not linked?

### ISSUE THREAD

**Issue by ArcheryMark** [Alcalol/IanseoParse#2]
Using pre-compiled jar 1.3.0, but it fails instantly with the following stack trace. Readme file says that all dependencies are included in the jar, but this stacktrace would imply that the jsoup libraries are not in there?

Tried with both Oracle JRE and the Adoptium/Eclipse one.

```
Error: A JNI error has occurred, please check your installation and try again
Exception in thread "main" java.lang.NoClassDefFoundError: org/jsoup/nodes/Element
        at java.lang.Class.getDeclaredMethods0(Native Method)
        at java.lang.Class.privateGetDeclaredMethods(Unknown Source)
        at java.lang.Class.privateGetMethodRecursive(Unknown Source)
        at java.lang.Class.getMethod0(Unknown Source)
        at java.lang.Class.getMethod(Unknown Source)
        at sun.launcher.LauncherHelper.validateMainClass(Unknown Source)
        at sun.launcher.LauncherHelper.checkAndLoadMain(Unknown Source)
Caused by: java.lang.ClassNotFoundException: org.jsoup.nodes.Element
        at java.net.URLClassLoader.findClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        ... 7 more
```

**Comment by shermanlo77** [comment]
Thanks for flagging this up. The releases 1.2, 1.3.0 and 1.3.1 are now `jar-with-dependencies`, does this work for you?
